create table if not exists public.clientes (
  id bigint generated by default as identity primary key,
  codigo varchar(30) not null,
  nome varchar(150) not null,
  contato varchar(60),
  endereco varchar(180),
  numero varchar(20),
  complemento varchar(80),
  bairro varchar(80),
  cidade varchar(80),
  uf varchar(2),
  cep varchar(20),
  created_at timestamp with time zone default now()
);

create unique index if not exists ux_clientes_codigo on public.clientes (codigo);

alter table public.clientes enable row level security;

drop policy if exists "Permitir leitura clientes" on public.clientes;
create policy "Permitir leitura clientes"
on public.clientes
for select
to anon, authenticated
using (true);

drop policy if exists "Permitir insercao clientes" on public.clientes;
create policy "Permitir insercao clientes"
on public.clientes
for insert
to anon, authenticated
with check (true);
