create table if not exists public.lancamentos_caixa (
  id bigint generated by default as identity primary key,
  data date not null,
  descricao text not null,
  categoria text not null,
  tipo text not null check (tipo in ('Entrada','Saída')),
  forma text not null,
  valor numeric(12,2) not null check (valor>0),
  observacao text,
  responsavel text not null check (responsavel in ('MEIRE','AIUMA','APARECIDA')),
  created_at timestamp with time zone default now() not null
);

create table if not exists public.aberturas_caixa (
  id bigint generated by default as identity primary key,
  data date not null unique,
  valor_inicial numeric(12,2) not null default 0,
  aberto_por text not null check (aberto_por in ('MEIRE','AIUMA','APARECIDA')),
  observacao text,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.fechamentos_caixa (
  id bigint generated by default as identity primary key,
  data date not null unique,
  total_entradas numeric(12,2) not null default 0,
  total_saidas numeric(12,2) not null default 0,
  saldo numeric(12,2) not null default 0,
  fechado_por text not null check (fechado_por in ('MEIRE','AIUMA','APARECIDA')),
  observacao text,
  created_at timestamp with time zone default now() not null
);

alter table public.lancamentos_caixa enable row level security;
alter table public.aberturas_caixa enable row level security;
alter table public.fechamentos_caixa enable row level security;

create policy if not exists "sel_l" on public.lancamentos_caixa for select to anon using (true);
create policy if not exists "ins_l" on public.lancamentos_caixa for insert to anon with check (true);
create policy if not exists "upd_l" on public.lancamentos_caixa for update to anon using (true) with check (true);
create policy if not exists "del_l" on public.lancamentos_caixa for delete to anon using (true);

create policy if not exists "sel_a" on public.aberturas_caixa for select to anon using (true);
create policy if not exists "ins_a" on public.aberturas_caixa for insert to anon with check (true);
create policy if not exists "upd_a" on public.aberturas_caixa for update to anon using (true) with check (true);
create policy if not exists "del_a" on public.aberturas_caixa for delete to anon using (true);

create policy if not exists "sel_f" on public.fechamentos_caixa for select to anon using (true);
create policy if not exists "ins_f" on public.fechamentos_caixa for insert to anon with check (true);
create policy if not exists "upd_f" on public.fechamentos_caixa for update to anon using (true) with check (true);
create policy if not exists "del_f" on public.fechamentos_caixa for delete to anon using (true);
