create table if not exists public.lancamentos_caixa (
  id bigint generated by default as identity primary key,
  data date not null,
  descricao text not null,
  categoria text not null,
  tipo text not null check (tipo in ('Entrada', 'Saída')),
  forma text not null,
  valor numeric(12,2) not null check (valor > 0),
  observacao text,
  responsavel text not null check (responsavel in ('MEIRE', 'AIUMA', 'APARECIDA')),
  created_at timestamp with time zone default now() not null
);

alter table public.lancamentos_caixa enable row level security;

drop policy if exists "liberar leitura lancamentos_caixa" on public.lancamentos_caixa;
drop policy if exists "liberar insercao lancamentos_caixa" on public.lancamentos_caixa;
drop policy if exists "liberar atualizacao lancamentos_caixa" on public.lancamentos_caixa;
drop policy if exists "liberar exclusao lancamentos_caixa" on public.lancamentos_caixa;

create policy "liberar leitura lancamentos_caixa"
on public.lancamentos_caixa
for select
to anon
using (true);

create policy "liberar insercao lancamentos_caixa"
on public.lancamentos_caixa
for insert
to anon
with check (true);

create policy "liberar atualizacao lancamentos_caixa"
on public.lancamentos_caixa
for update
to anon
using (true)
with check (true);

create policy "liberar exclusao lancamentos_caixa"
on public.lancamentos_caixa
for delete
to anon
using (true);

insert into public.lancamentos_caixa
(data, descricao, categoria, tipo, forma, valor, observacao, responsavel)
values
('2026-04-13', 'Venda de armação + lentes', 'Venda', 'Entrada', 'Pix', 780.00, 'Cliente pagou à vista', 'MEIRE'),
('2026-04-13', 'Pagamento de fornecedor', 'Fornecedor', 'Saída', 'Transferência', 320.00, 'Compra de lentes', 'AIUMA'),
('2026-04-14', 'Retirada do caixa', 'Retirada', 'Saída', 'Dinheiro', 100.00, 'Despesa emergencial', 'APARECIDA');
