create table if not exists public.lancamentos_caixa (
  id bigint generated by default as identity primary key,
  data date not null,
  descricao text not null,
  categoria text not null,
  tipo text not null check (tipo in ('Entrada', 'Saída')),
  forma text not null,
  valor numeric(12,2) not null check (valor > 0),
  observacao text,
  responsavel text not null check (responsavel in ('MEIRE', 'AIUMA', 'APARECIDA')),
  created_at timestamp with time zone default now() not null
);

create table if not exists public.fechamentos_caixa (
  id bigint generated by default as identity primary key,
  data date not null unique,
  total_entradas numeric(12,2) not null default 0,
  total_saidas numeric(12,2) not null default 0,
  saldo numeric(12,2) not null default 0,
  fechado_por text not null check (fechado_por in ('MEIRE', 'AIUMA', 'APARECIDA')),
  observacao text,
  created_at timestamp with time zone default now() not null
);

alter table public.lancamentos_caixa enable row level security;
alter table public.fechamentos_caixa enable row level security;

drop policy if exists "liberar leitura lancamentos_caixa" on public.lancamentos_caixa;
drop policy if exists "liberar insercao lancamentos_caixa" on public.lancamentos_caixa;
drop policy if exists "liberar atualizacao lancamentos_caixa" on public.lancamentos_caixa;
drop policy if exists "liberar exclusao lancamentos_caixa" on public.lancamentos_caixa;

create policy "liberar leitura lancamentos_caixa"
on public.lancamentos_caixa for select to anon using (true);

create policy "liberar insercao lancamentos_caixa"
on public.lancamentos_caixa for insert to anon with check (true);

create policy "liberar atualizacao lancamentos_caixa"
on public.lancamentos_caixa for update to anon using (true) with check (true);

create policy "liberar exclusao lancamentos_caixa"
on public.lancamentos_caixa for delete to anon using (true);

drop policy if exists "liberar leitura fechamentos_caixa" on public.fechamentos_caixa;
drop policy if exists "liberar insercao fechamentos_caixa" on public.fechamentos_caixa;
drop policy if exists "liberar atualizacao fechamentos_caixa" on public.fechamentos_caixa;
drop policy if exists "liberar exclusao fechamentos_caixa" on public.fechamentos_caixa;

create policy "liberar leitura fechamentos_caixa"
on public.fechamentos_caixa for select to anon using (true);

create policy "liberar insercao fechamentos_caixa"
on public.fechamentos_caixa for insert to anon with check (true);

create policy "liberar atualizacao fechamentos_caixa"
on public.fechamentos_caixa for update to anon using (true) with check (true);

create policy "liberar exclusao fechamentos_caixa"
on public.fechamentos_caixa for delete to anon using (true);
